version: "3"
services:
  api:
    build: .
    environment:
      - MONGOURI=mongodb://mongo/elitetapp
      - DATABASE_URL=postgres://admin:admin@db/elitetapp
      - PORT=5000
    ports:
      - 5000:5000
      - 9229:9229
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - mongo
      - db
    command: npm run dev:docker

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=elitetapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  node_modules:
  postgres-data:
