version: "3"
services:
  api:
    build: .
    environment:
      - MONGOURI=mongodb://mongo/elitetapp
      - PORT=5000
    ports:
      - 5000:5000
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - mongo
    command: npm run dev:docker

  mongo:
    image: mongo
    ports:
      - "27017:27017"

volumes:
  node_modules:
