version: "3"
services:
  api:
    build: .
    environment:
      - DATABASE_URL=postgres://admin:admin@db/elitetapp
      - REDIS_PRIMARY_URL=redis://redis:6379
      - REDIS_QUEUE_URL=redis://redis:6379/1
      - PORT=5000
    ports:
      - 5000:5000
      - 9229:9229
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - db
    command: npm run dev:docker

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=elitetapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6378:6379"
    volumes:
      - "redis_data:/data"

volumes:
  node_modules:
  postgres-data:
  redis_data:
