// events
const TEST = 'TEST';
const INITIAL_PURCHASE = 'INITIAL_PURCHASE';
const NON_RENEWING_PURCHASE = 'NON_RENEWING_PURCHASE';
const RENEWAL = 'RENEWAL';
const PRODUCT_CHANGE = 'PRODUCT_CHANGE';
const CANCELLATION = 'CANCELLATION';
const UNCANCELLATION = 'UNCANCELLATION';
const BILLING_ISSUE = 'BILLING_ISSUE';
const SUBSCRIBER_ALIAS = 'SUBSCRIBER_ALIAS';
const SUBSCRIPTION_PAUSED = 'SUBSCRIPTION_PAUSED';

// cancellation
const UNSUBSCRIBE = 'UNSUBSCRIBE';
const BILLING_ERROR = 'BILLING_ERROR';
const DEVELOPER_INITIATED = 'DEVELOPER_INITIATED';
const PRICE_INCREASE = 'PRICE_INCREASE';
const CUSTOMER_SUPPORT = 'CUSTOMER_SUPPORT';
const UNKNOWN = 'UNKNOWN';

// periods
const TRIAL = 'TRIAL';
const INTRO = 'INTRO';
const NORMAL = 'NORMAL';
const PROMOTIONAL = 'PROMOTIONAL';

module.exports = {
  events: {
    TEST,
    INITIAL_PURCHASE,
    NON_RENEWING_PURCHASE,
    RENEWAL,
    PRODUCT_CHANGE,
    CANCELLATION,
    UNCANCELLATION,
    BILLING_ISSUE,
    SUBSCRIBER_ALIAS,
    SUBSCRIPTION_PAUSED,
  },
  cancellationReasons: {
    UNSUBSCRIBE,
    BILLING_ERROR,
    DEVELOPER_INITIATED,
    PRICE_INCREASE,
    CUSTOMER_SUPPORT,
    UNKNOWN,
  },
  periodTypes: {
    TRIAL,
    INTRO,
    NORMAL,
    PROMOTIONAL,
  },
};
