openapi: "3.0.2"
info:
  title: Elite Tapp API
  version: "1.0.0"
servers:
  - url: http://localhost:5000/api/v1
  - url: https://api-elite-tapp.com/api/v1
paths:
  /test:
    get:
      responses:
        "200":
          description: OK
